//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Menu
    {
        public int MenuID { get; set; }
        public string MenuName { get; set; }
        public int ParentID { get; set; }
        public string URL { get; set; }
        public string Icon { get; set; }
        public int OrderMenu { get; set; }
        public bool IsShow { get; set; }
        public bool Active { get; set; }
    }
}
