//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_CateProduct
    {
        public int CategoyID { get; set; }
        public string Name { get; set; }
        public int ParentID { get; set; }
        public bool Active { get; set; }
        public string CateURL { get; set; }
        public string ImgHomePage { get; set; }
    }
}
