//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_Log
    {
        public int LogID { get; set; }
        public int UserID { get; set; }
        public string Title { get; set; }
        public string ContentLog { get; set; }
        public System.DateTime Date { get; set; }
        public string Fullname { get; set; }
    }
}
