//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_MenuRole
    {
        public int RoleMenuID { get; set; }
        public int RoleID { get; set; }
        public int MenuID { get; set; }
        public bool ViewData { get; set; }
        public bool AddData { get; set; }
        public bool EditData { get; set; }
        public bool DelData { get; set; }
        public bool Import { get; set; }
        public bool Export { get; set; }
    }
}
