//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Tags
    {
        public int TagID { get; set; }
        public string TagName { get; set; }
        public int CountTag { get; set; }
        public string URL { get; set; }
    }
}
