//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_PortfolioCategory
    {
        public int PortfolioCateID { get; set; }
        public int PortfolioID { get; set; }
        public int CateID { get; set; }
    }
}
