//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Post
    {
        public int PostId { get; set; }
        public string PostTitle { get; set; }
        public string PostContent { get; set; }
        public string PostType { get; set; }
        public Nullable<int> PostAuthor { get; set; }
        public Nullable<System.DateTime> PostCreateDate { get; set; }
        public string PostFaceImage { get; set; }
        public string PostSeoDesc { get; set; }
        public string PostSeoKeyword { get; set; }
        public string URLFriendly { get; set; }
        public string PostDescription { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> PostUpdateDate { get; set; }
        public int CountView { get; set; }
        public bool IsHome { get; set; }
        public string Tags { get; set; }
    }
}
