//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Config
    {
        public int ConfigID { get; set; }
        public string CompanyName { get; set; }
        public string Hotline { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Facebook { get; set; }
        public string GooglePlus { get; set; }
        public string Youtube { get; set; }
        public string CodeAnalytics { get; set; }
    }
}
