//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Portfolio
    {
        public int PortfolioId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<int> Author { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ImageFace { get; set; }
        public string ImgGallery { get; set; }
        public string SeoDesc { get; set; }
        public string SeoKeyword { get; set; }
        public string URLFriendly { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
